[build-system]
requires = [
    "hatchling>=1.27.0",
    "vapoursynth>=80",
    "meson",
    "ninja",
    "packaging",
]
build-backend = "hatchling.build"

[project]
name = "vapoursynth-knlmeansvk"
dynamic = ["version"]
description = "Non-local means de-noising on the VapourSynth Vulkan GPU device"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.12"
authors = [{ name = "Edoardo Brunetti", email = "edo.brunetti@gmail.com" }]
maintainers = [
    { name = "Jaded Encoding Thaumaturgy", email = "jaded.encoding.thaumaturgy@gmail.com" },
]
dependencies = ["vapoursynth>=80"]

[dependency-groups]
dev = ["hatchling>=1.27.0", "packaging"]

[project.urls]
"Source Code" = "https://github.com/Jaded-Encoding-Thaumaturgy/vapoursynth-knlmeansvk"
"Bug Tracker" = "https://github.com/Jaded-Encoding-Thaumaturgy/vapoursynth-knlmeansvk/issues"
"Changelog" = "https://github.com/Jaded-Encoding-Thaumaturgy/vapoursynth-knlmeansvk/blob/master/CHANGELOG"
"Contact" = "https://discord.gg/XTpc6Fa9eB"

[tool.hatch.version]
path = "meson.build"
pattern = "version\\s*:\\s*'(?P<version>\\d+\\.\\d+)'"

[tool.hatch.build.targets.sdist]
include = ["lib", "meson.build", "meson_options.txt"]

[tool.hatch.build.targets.wheel]
include = ["vapoursynth/plugins"]
artifacts = [
    "vapoursynth/plugins/*.dylib",
    "vapoursynth/plugins/*.so",
    "vapoursynth/plugins/*.dll",
]

[tool.hatch.build.targets.wheel.hooks.custom]
path = "hatch_build.py"
