name: Build for macOS

on:
  workflow_call:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: macosx_x86_64
            runs-on: macos-15-intel
          - arch: macosx_arm64
            runs-on: macos-15
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6

      - name: Fetch Vulkan headers
        run: git clone --depth 1 https://github.com/KhronosGroup/Vulkan-Headers.git vulkan-headers

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4
        env:
          CIBW_BUILD: cp312-*
          CIBW_BUILD_FRONTEND: uv
          CIBW_ENVIRONMENT_MACOS: >
            MESON_ARGS="-Dvulkan_include=${{ github.workspace }}/vulkan-headers/include"
            MACOSX_DEPLOYMENT_TARGET=15
        with:
          extras: uv

      - name: Upload VapourSynth plugin
        uses: actions/upload-artifact@v7
        with:
          name: knlmeansvk-vs-macos-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
