name: Build for Linux

on:
  workflow_call:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4
        env:
          CIBW_BUILD: cp312-*
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_BUILD_FRONTEND: uv
          CIBW_BEFORE_ALL_LINUX: >
            git clone --depth 1 https://github.com/KhronosGroup/Vulkan-Headers.git /opt/vulkan-headers
          CIBW_ENVIRONMENT: MESON_ARGS="-Dstatic=true -Dvulkan_include=/opt/vulkan-headers/include"
          CIBW_SKIP: "*-musllinux*"
        with:
          extras: uv

      - name: Upload VapourSynth plugin
        uses: actions/upload-artifact@v7
        with:
          name: knlmeansvk-vs-linux-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
